version: 1.4.{build}

install:
  - ps: Install-Product node 5
  - npm install -g tsd
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install

build_script:
  - gulp build

test_script:
  - gulp test

notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: GniMpFE62HprSyQNQoej/fBOAdbQe8EMWAMMNXX0s2JxeNePjemiO1bCf4eYweE4p70mm0sCwMjeEP/Ps9aTMA==
