version: 1.1.{build}

install:
  - ps: Install-Product node 4
  - npm install -g tsd
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - tsd reinstall -s
  - bower install

build_script:
  - gulp build

test_script:
  - gulp test

notifications:
  - provider: Slack
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
    channel: notifications
