version: 0.1.{build}

environment:
  nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - cd src
  - npm install -g bower
  - npm install
  - bower install

build_script:
  - gulp build

test_script:
  - gulp test
  
after_test:
  - cd ..
  - ps: nuget pack -Version $env:APPVEYOR_BUILD_VERSION

artifacts:
  - path: '*.nupkg'

notifications:
  - provider: Slack
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
    channel: notifications