version: 1.3.{build}

install:
  - ps: Install-Product node 5
  - npm install -g typings
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install

build_script:
  - gulp build

test_script:
  - gulp test

notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
